// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naqnlslxcipgsgbqbrdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcW5sc2x4Y2lwZ3NnYnFicmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NzY2ODMsImV4cCI6MjA1MTQ1MjY4M30.sdfNUBQeFc8Nv0wCO_NFPomqk-0HqTMNdrCSOzVsH8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);